export type PixelPalette = Record<string, string>;

const gridArt = (source: string): string[] => {
  const rows = source.trim().split("\n").map((line) => line.trim());
  if (rows.length !== 40) throw new Error(`Pet art must contain 40 rows, got ${rows.length}`);
  return rows.map((row, index) => {
    if (row.length > 32) throw new Error(`Pet art row ${index} is ${row.length} cells wide`);
    return row.padEnd(32, ".");
  });
};

// MCU-era Banner cues: wavy side-swept brown hair, narrow tired face, heavy brows,
// five-o'clock shadow, dark blue shirt, rolled sleeves, and a guarded posture.
export const BANNER_PALETTE: PixelPalette = {
  K: "#1a252b",
  H: "#49332f",
  h: "#2b2425",
  S: "#d89673",
  s: "#a85f50",
  L: "#efb08a",
  B: "#49332f",
  Q: "#dbe5dc",
  X: "#293735",
  N: "#b76c57",
  F: "#76504b",
  m: "#6e3e3f",
  C: "#3c5866",
  c: "#263f4d",
  W: "#c6ccd0",
  P: "#444a50",
  p: "#2d3439",
  Y: "#1d2529",
};

export const HULK_PALETTE: PixelPalette = {
  K: "#172329",
  H: "#282427",
  G: "#579947",
  L: "#82be5a",
  D: "#315f38",
  B: "#294b31",
  Q: "#e0e3c9",
  X: "#17251d",
  N: "#477d3e",
  M: "#4c2d31",
  T: "#e5dac0",
  P: "#52335f",
  p: "#36263f",
  Y: "#25312a",
};

export const SURGE_PALETTE: PixelPalette = {
  ...BANNER_PALETTE,
  G: "#579947",
  D: "#315f38",
  R: "#76868b",
};

export const BANNER_ART = gridArt(`
............hhhHHHH.............
..........hhhHHHHHHhh..........
.........hhHHHHHHHHHhh.........
........hhHHHHHHHHHHHh.........
.......hKHHHHHHHHHHHhhK........
.......hKSSSSSSSSSSSSSKh........
.......KSSSSSSSSSSSSSSSK........
......KSSSBBBSSSSBBBSSSSK.......
......KSSBQXSSSSSQXBSSSSK.......
......KSSSSSSssSSSSSSSSK.......
......KSSSSSSNssSSSSSSSK.......
.......KSSSFFFmFFFFSSSSK.......
........KSSFFFFFFssSSSSK........
.........KKSSSSSSSSSKK..........
...........KSSSSSSK.............
..........KKCCWWCCKK............
.........KCCCCCCCCCCK...........
........KCCCCCCCCCCCCK..........
.......KCCCCCCCCCCCCCCK.........
......KSSCCCCCCCCCCCCSSK........
......KSSCCCCCCCCCCCCSSK........
.......KCCCCCCCCCCCCCCK.........
........KCCCCCCCCCCCCK..........
.........KCCCCCCCCCCK...........
.........KKccccccccKK...........
..........KPPPPPPPPK............
.........KPPPPPPPPPPK...........
........KPPPPPPPPPPPPK..........
........KPPPPPPPPPPPPK..........
........KPPPPPPPPPPPPK..........
........KPPPPPP..PPPPK..........
........KPPPPPP..PPPPK..........
........KPPPPPP..PPPPK..........
.......KKPPPPPP..PPPPKK.........
.......KPPPPPP....PPPPK.........
......KKPPPPPP....PPPPKK........
......KYYYYYK......KYYYYK.......
.....KKYYYYYK......KYYYYKK......
.....KKKKKKKK......KKKKKKK......
................................
`);

export const BANNER_TIRED_ART = BANNER_ART.map((row, index) => {
  if (index === 7) return row.replace(/B/g, "F");
  if (index === 8) return row.replace(/BQX/g, "FXX").replace(/QXB/g, "XXF");
  if (index === 11) return row.replace("m", "s");
  if (index === 12) return row.replace("FFFFFF", "FFmmFF");
  return row;
});

// Hulk keeps Banner's close-set eyes and central nose but pushes every large-form cue:
// low brow, square jaw, no visible neck, trapezius into shoulders, long forearms and fists.
export const HULK_ART = gridArt(`
.........KKHHHHHHHHKK...........
.......KKHHHHHHHHHHHHKK.........
......KHHHHHHHHHHHHHHHHK........
.....KHHHHHHHHHHHHHHHHHHK.......
.....KGGGGGGGGGGGGGGGGGGK.......
....KGGGDDDGGGGGGGGGDDDGGGK.....
....KGGGGGDDDDGGGDDDDGGGGGK....
....KGGGGQXXGGGGGXXQGGGGGK.....
....KGGGGGGGGNNNNGGGGGGGGK.....
....KGGGGGGMMMMMMMMGGGGGGK.....
.....KGGGGGMTTTTTTTMGGGGGK......
.....KKGGGGGGMMMMGGGGGGKK......
.....KKKDDGGGGGGGGGGGDDKKK.....
....KKDDGGGGGGGGGGGGGGDDKK.....
...KKDDGGGGGGGGGGGGGGGGDDKK....
..KKDDGGGGGGGGGGGGGGGGGGDDKK...
.KKGGGGGGGGGGGGGGGGGGGGGGGGGGKK.
KKGGGGGGGGGGGGGGGGGGGGGGGGGGGGKK
KDDGGGGGGGGGGGGGGGGGGGGGGGGGGDDK
KDDGGGGGGGGDDDDGGGGDDDDGGGGGGDDK
KDDGGGGGGGGDDDDGGGGDDDDGGGGGGDDK
KKDDGGGGGGGGGGGGGGGGGGGGGGGGDDKK
KKKDDGGGGGGGGGGGGGGGGGGGGGGDDKKK
.KKKDDGGGGGGGGGGGGGGGGGGGGDDKKK.
..KKKGGGGGGGGGGGGGGGGGGGGGKKK..
...KKGGGGGGGGGGGGGGGGGGGGGGKK...
....KKGGGGGGGGGGGGGGGGGGGGKK....
.....KKGGGGGGGGGGGGGGGGGGKK.....
.....KKKPPPPPPPPPPPPPPPPKKK.....
....KKPPPPPPPPPPPPPPPPPPPPKK....
....KPPPPPPPPPPPPPPPPPPPPPPK....
...KKPPPPPPPPPPPPPPPPPPPPPPKK...
...KPPPPPPPPPPPPPPPPPPPPPPPPK...
...KPPPPPPPP..PP..PPPPPPPPPPK...
...KPPPPPPPP..PP..PPPPPPPPPPK...
..KKPPPPPPPP..PP..PPPPPPPPPPKK..
..KYYYYYYYYY...YY...YYYYYYYYYK..
.KKYYYYYYYYY...YY...YYYYYYYYYKK.
.KKKKKKKKKKK...KK...KKKKKKKKKK..
................................
`);

export const SURGE_ART = BANNER_ART.map((row, index) => {
  if (index >= 5 && index <= 14) return row.replace(/[SsLN]/g, "G").replace(/F/g, "D");
  if (index >= 15 && index <= 24) return row.replace(/C/g, "R").replace(/c/g, "D");
  if (index >= 25 && index <= 37) return row.replace(/P/g, "G").replace(/p/g, "D");
  return row;
});
